### ISSUE TITLE
2 maps one document type - errors

### ISSUE THREAD

**Issue by kennyburns1967** [netaddicts/umbraco-v7-property-editors-gmaps#15]
Hello,

I am using 2 instances of a Google Maps datatype on one document type and its is causing a javascript error. It won't load load either of the maps. The error seems to be a google maps issue though:

maps.gstatic.com/cat_js/maps-api-v3/api/js/18/17/%7Bmain,places%7D.js:57 - Uncaught TypeError: undefined is not a function
Have you come across this?

Thanks,

Kenny

**Comment by TimGeyssens** [comment]
Seems to be fixed by pull request 21 https://github.com/netaddicts/umbraco-v7-property-editors-gmaps/pull/21
