### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by kipusoep** [netaddicts/umbraco-v7-property-editors-gmaps#17]
It would be great if you could create a NuGet package of this editor.

**Comment by cheeseytoastie** [comment]
Have you missed this? 

https://www.nuget.org/packages/umbraco-v7-property-editors-gmaps

**Comment by kipusoep** [comment]
No, I made it ;-)
Just forgot to close this issue.

![image](https://cloud.githubusercontent.com/assets/1866549/9132488/2d7975ee-3cf4-11e5-8961-badc5eff9b0c.png)

**Comment by cheeseytoastie** [comment]
Haha! Brilliant! Well thanks for making the Nuget package! Just used it - very useful :)
