### ISSUE TITLE
Load resources over protocol relative uri's

### ISSUE THREAD

**Issue by netaddicts** [netaddicts/umbraco-v7-property-editors-gmaps#9]
See http://our.umbraco.org/projects/backoffice-extensions/google-maps-property-editor-w-google-places-autocomplete-lookup/bugs,-feedback-and-suggestions/53982-Load-resources-over-protocol-relative-URIs

Inside of the GMaps.controller.js file, instead of using:

assetsService.loadJs('http://www.google.com/jsapi')
    .then(function () {
Consider using:

assetsService.loadJs('//www.google.com/jsapi')
    .then(function () {
The use of a protocol relative URI will stop any errors/blocked loading of the script when running the site under HTTPS.

**Comment by TimGeyssens** [comment]
Seems to be done...
